# PLEASE NOTE: This is a work in progress if there ever was one. 
# I am still trying to figure out how this works before I switch
# to wayland.

# icon: &icon  Material Design Icons:style=Regular:pixelsize=18
# tags: &tags Material Design Icons:style=Regular:pixelsize=22

# bar:
#   height: 36
#   location: top
#   layer: bottom
#   spacing: 5
#   font: Iosevka Term:size=28:weight=regular
#   left-margin: 10
#   right-margin: 10
#   foreground: F1F1F1FF
#   background: 11111100
#   
#   right:
#     - clock:
#         time-format: "%I:%M"
#         date-format: "%a %d"
#         content:
#           - string: {text: "[ 󰥔 {time} {date} ]"}
#   left:
#     - dwl:
#         number-of-tags: 6
        
bar:
  location: top
  height: 26
  background: 000000ff
  border:
    left-margin: 10
    right-margin: 10
    top-margin: 5
    bottom-margin: 5
    color: 00000000
  font: Iosevka:size=14
  

  right:
    #    - network:
    #        name: wlan0
    #        content:
    #          map:
    #            tag: state
    #            values:
    #              up: {string: {text: "{ssid}", right-margin: 8}}
    #              down: {string: {text: "No internet connection", right-margin: 8}}
    - clock:
        time-format: "%H:%M"
        date-format: "%m/%d (%a)"
        content:
          string: {text: "{date} {time}", right-margin: 5, deco: {underline: {size: 2, color: ffffffff}}}

  # center:
  #   - i3:
  #       content:
  #         current:
  #           - string: {text: "{application}"}
  # left:
  #   - i3:
  #       content:
  #         "":
  #           map:
  #             tag: state
  #             default: {string: {text: "{name}", margin: 8}}
  #             values:
  #               focused:
  #                 string:
  #                   deco: {underline: {size: 2, color: FFFFFFFF}}
  #                   text: "{name}"
  #                   margin: 8
