#!/bin/sh

super="Mod4"
hyper="Mod4+Shift+Control+Mod1"
ctrl="Control"
alt="Mod1"

########################
## Modes and bindings ##
########################
riverctl declare-mode docked
riverctl map normal $hyper D spawn "$XDG_CONFIG_HOME/river/dock"
riverctl map docked $hyper D spawn "$XDG_CONFIG_HOME/river/dock -u"
for mode in normal docked 
do
	# Spawn Terminal
	riverctl map $mode $super+Shift Return spawn alacritty
	
	# Close window
	riverctl map $mode $super+Shift C close
	
	# Exit
	riverctl map $mode $hyper Q exit
	
	# fuzzel programs
	riverctl map $mode $super P spawn fuzzel
	
	# fuzzel run
	riverctl map $mode $super R spawn fuzzel-run
	
	# Spawn emacs 
	riverctl map $mode $super E spawn "emacsclient -c" 
	
	# Spawn browser
	riverctl map $mode $super+Shift B spawn firefox-wayland
	
	# Spawn browser
	riverctl map $mode $super+Shift P spawn keepassxc
	
	# Spawn Home
	riverctl map $mode $super N spawn nhome
	
	# Waylock
	riverctl map $mode $super+Control L spawn 'waylock -init-color 0x2e3440 -input-color 0x5e81ac -fail-color 0xbf616a'
	
	# Pulsemixer
	riverctl map $mode $super M spawn 'alacritty --class float -e pulsemixer'

	# ncmpcpp
	riverctl map $mode $super+Shift M spawn 'alacritty --class float -e ncmpcpp'

	# top/btm
	riverctl map $mode $super+Shift T spawn 'alacritty --class float -e btm'

	# Screenshots with grim/slurp
	riverctl map $mode $super S spawn 'grim - | tee $HOME/pix/ss/$(date +%Y%m%d-%s)-screenshot.png | wl-copy'

	# Screenshot Regions with grim/slurp
	riverctl map $mode $super+Shift S spawn 'grim -g "$(slurp)" - | tee $HOME/pix/ss/$(date +%Y%m%d-%s)-screenshot.png | wl-copy'

	# Audio commands
	riverctl map -repeat $mode None XF86AudioLowerVolume spawn 'volume-changer d'
	riverctl map -repeat $mode None XF86AudioRaiseVolume spawn 'volume-changer i'
	riverctl map -repeat $mode None XF86AudioMute spawn 'volume-changer'
	
	# Mod+J and Mod+K to focus the next/previous view in the layout stack
	riverctl map $mode $super J focus-view next
	riverctl map $mode $super K focus-view previous
	
	# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
	riverctl map $mode $super H send-layout-cmd rivertile "main-ratio -0.05"
	riverctl map $mode $super L send-layout-cmd rivertile "main-ratio +0.05"
	
	# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
	riverctl map $mode $super I send-layout-cmd rivertile "main-count +1"
	riverctl map $mode $super D send-layout-cmd rivertile "main-count -1"

	# Mod+Space to toggle floating window
	riverctl map $mode $super Space toggle-float
	riverctl map $mode $super+Shift F toggle-float
	riverctl map -repeat $mode $super+Shift H move left 20
	riverctl map -repeat $mode $super+Shift L move right 20
	riverctl map -repeat $mode $super+Shift J move down 20
	riverctl map -repeat $mode $super+Shift K move up 20

	# Mod+F to toggle fullscreen
	riverctl map $mode $super F toggle-fullscreen
	
	#setting up tags
	for i in $(seq 1 6)
	do
		tags=$((1 << ($i - 1)))
		
		# Mod4+[1-6] to focus tag [0-5]
		riverctl map $mode $super $i set-focused-tags $tags
		
		# Mod4+Shift+[1-6] to tag focused view with tag [0-5]
		riverctl map $mode $super+Shift $i set-view-tags $tags
		
		# Mod4+Ctrl+[1-6] to toggle focus of tag [0-5]
		riverctl map $mode $super+Control $i toggle-focused-tags $tags
		
		# Mod4+Shift+Ctrl+[1-6] to toggle tag [0-5] of focused view
		riverctl map $mode $super+Shift+Control $i toggle-view-tags $tags
	done
	
	#super+0 to focus on all tags
	all_tags=$(((1 << 6) - 1))
	riverctl map $mode Mod4 0 set-focused-tags $all_tags
	riverctl map $mode Mod4+Shift 0 set-view-tags $all_tags
done

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "Firefox - Choose User Profile"

#default layouts
riverctl default-layout rivertile
rivertile -view-padding 1 -outer-padding 2 &

#keyboard layout
riverctl keyboard-layout -options ctrl:swapcaps us

#yambar
yambar-bar-controller-script
yambar-bar-controller-script -s 

#wlr-rander
wlr-randr --output eDP-1 --scale 2

#wallpaper and colors
riverctl background-color 0x3b4252
riverctl border-color-focused 0x88c0d0
riverctl border-color-unfocused 0x4c566a
riverctl border-color-urgent 0xd08770

wayland-wallpaper-set -l

#spawn programs
if [ -z $(pgrep emacs)]; then
	setsid -f emacs --daemon &
fi
riverctl spawn mpd &
pkill dunst && riverctl spawn dunst &

#home
riverctl spawn nhome
