#!/bin/sh

case "$1" in
	*.tgz|*.tar.gz) tar tzf "$1";;
	*.tar.bz2|*.tbz2) tar tjf "$1";;
	*.tar.txz|*.txz) xz --list "$1";;
	*.tar) tar tf "$1";;
	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1";;
	*.7z) 7z l "$1";;
	*.[1-8]) man "$1" | col -b ;;
	*.o) nm "$1" ;;
	*.iso) iso-info --no-header -l "$1";;
	*.csv) cat "$1" | sed s/,/\\n/g ;;
	*.pdf) pdftotxt "$1" -;; 
	*.bmp|*.gif|*.jpg|*.jpeg|*.png|*.xpm) chafa --animate off --size "$2x$3" "$1";;
	*.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.flac) exiftool "$1";;
	*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx) exiftool "$1";;
	*) highlight --out-format ansi "$1" || cat "$1";;
esac
