#!/bin/bash

#system aliases
alias cd="__zoxide_z"
alias icd="__zoxide_zi"
alias cl="clear"
alias ls='ls --color=auto'
alias mkcd="mkcd"
alias mv="mv -i"
alias cp="cp -i"
alias rm="rm -I"
alias wget="wget --no-hsts"
alias info="info --vi-keys"
#alias xu="sudo xbps-install -u xbps && sudo xbps-install -Su && sudo xbps-remove -o && xlocate -S" 
#alias xi="sudo xbps-install"
alias xs="xrs"
alias xr="sudo xbps-remove -R"
alias zpt="zellij -l worktag"
alias zel="zellij"
alias zc="zuluCrypt-cli"
alias zm="zuluMoutn-cli"
alias vpnd="sudo protonvpn d && sleep 1.5 && pkill -RTMIN+10 dwmblocks"
alias vpnc="sudo protonvpn c && sleep 1.5 && pkill -RTMIN+10 dwmblocks"
alias vpnr="sudo protonvpn c -r && sleep 1.5 && pkill -RTMIN+10 dwmblocks"

#shortening 
alias emnw="emacsclient -t -a ''"
alias YT="ytfzf -T chafa" #you might have to detach at 00939e8
alias YTO="ytfzf -T chafa -c O"
alias YTM="ytfzf -T chafa -t -s -m"
alias yt="vidDownloader"
alias z="zathura" #original: alias z="zathura --fork"
alias am="amfora"
alias mg="manga-cli -l -f"
alias c="wordCompiler"
alias t="task"
alias del="trash-put"
alias scim="sc-im"
alias ffox="ffox"
alias lr="lr"
alias rw="rw"
alias remindme="less $HOME/.local/share/remindme/remindme.txt"
alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'
alias irssi='irssi --config="$XDG_CONFIG_HOME"/irssi/config --home="$XDG_DATA_HOME"/irssi'

#colourizing
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"
